name: icudg 
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
- python=3.9.12
- numpy=1.23.4
- pandas=1.5.1
- pyarrow=9.0.0
- pytorch=1.12.1
- scikit-learn=1.1.3
- tqdm=4.64.1
- pip=22.3.1
- matplotlib=3.6.1
- pyyaml=6.0
- tqdm=4.64.1
- backpack-for-pytorch=1.5.0
